default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: scrumflow_admin_development
    username: postgres
    password: postgres
    host: localhost
    port: 5433

  scrumflow:
    <<: *default
    database: scrumflow_production
    username: postgres
    password: dcceec4c9a66df50fe8a
    host: 82.25.77.197
    port: 5432
    sslmode: disable
    database_tasks: false

test:
  primary:
    <<: *default
    database: scrumflow_admin_test
    username: postgres
    password: postgres
    host: localhost
    port: 5433

production:
  primary:
    <<: *default
    database: sfadmin
    username: postgres
    password: e343d790a0d58eeda9dc
    host: sfadmin-sfadmindb
    port: 5432

  scrumflow:
    <<: *default
    url: postgresql://postgres:dcceec4c9a66df50fe8a@tudogratis_scrumflow-postgres:5432/scrumflow_production?sslmode=disable
    database_tasks: false